base: core18
name: opentrack
version: 3.0.0.dev0
summary: head tracking for games and flight simulators
description: |
    opentrack is an application dedicated to tracking user's head movements and relaying the information to games and flight simulation software

confinement: devmode
grade: devel

apps:
    opentrack:
        command: qt5-launch bin/opentrack
        plugs: [camera]
        environment:
            LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$SNAP/lib/opentrack

parts:
    arucosdk:
        plugin: cmake
        source: https://github.com/opentrack/aruco.git

    opentrack:
        plugin: cmake
        configflags:
            - -DSDK_ARUCO_LIBPATH:FILEPATH=/mnt/opentrack/snap/parts/arucosdk/build/src/libaruco.a
        # Why oh why if i specify source as ".." does that become "/mnt/opentrack/parts/opentrack/src"?
        source: /mnt/opentrack  # TODO change source to git
        build-packages:
            # How to make this DEBIAN_FRONTEND=noninteractive? stupid tzdata!
            # Work around is to install tzdata to the system beforehand.
            - g++
            - libevdev-dev
            - libopencv-dev
            - libprocps-dev
            - make
            - pkg-config
            - qtbase5-dev
            - qttools5-dev
            - qttools5-dev-tools
        stage-packages:
            - libqt5gui5
        after:
            - qt5conf
            - arucosdk
